void *glAlphaFunc(void) { return 0; }
void *glBindTexture(void) { return 0; }
void *glBitmap(void) { return 0; }
void *glBlendFunc(void) { return 0; }
void *glCallList(void) { return 0; }
void *glCallLists(void) { return 0; }
void *glClear(void) { return 0; }
void *glClearColor(void) { return 0; }
void *glClearDepth(void) { return 0; }
void *glClearStencil(void) { return 0; }
void *glClipPlane(void) { return 0; }
void *glColor4fv(void) { return 0; }
void *glColorMask(void) { return 0; }
void *glColorMaterial(void) { return 0; }
void *glColorPointer(void) { return 0; }
void *glCopyPixels(void) { return 0; }
void *glCopyTexImage1D(void) { return 0; }
void *glCopyTexImage2D(void) { return 0; }
void *glCopyTexSubImage1D(void) { return 0; }
void *glCopyTexSubImage2D(void) { return 0; }
void *glCullFace(void) { return 0; }
void *glDeleteLists(void) { return 0; }
void *glDeleteTextures(void) { return 0; }
void *glDepthFunc(void) { return 0; }
void *glDepthMask(void) { return 0; }
void *glDepthRange(void) { return 0; }
void *glDisable(void) { return 0; }
void *glDisableClientState(void) { return 0; }
void *glDrawArrays(void) { return 0; }
void *glDrawBuffer(void) { return 0; }
void *glDrawElements(void) { return 0; }
void *glDrawPixels(void) { return 0; }
void *glEnable(void) { return 0; }
void *glEnableClientState(void) { return 0; }
void *glEndList(void) { return 0; }
void *glFinish(void) { return 0; }
void *glFlush(void) { return 0; }
void *glFrontFace(void) { return 0; }
void *glGenLists(void) { return 0; }
void *glGenTextures(void) { return 0; }
void *glGetBooleanv(void) { return 0; }
void *glGetError(void) { return 0; }
void *glGetFloatv(void) { return 0; }
void *glGetIntegerv(void) { return 0; }
void *glGetPointerv(void) { return 0; }
void *glGetString(void) { return 0; }
void *glGetTexEnviv(void) { return 0; }
void *glGetTexImage(void) { return 0; }
void *glGetTexLevelParameterfv(void) { return 0; }
void *glGetTexLevelParameteriv(void) { return 0; }
void *glGetTexParameterfv(void) { return 0; }
void *glGetTexParameteriv(void) { return 0; }
void *glHint(void) { return 0; }
void *glIndexPointer(void) { return 0; }
void *glIsEnabled(void) { return 0; }
void *glIsTexture(void) { return 0; }
void *glLightModelfv(void) { return 0; }
void *glLightModeli(void) { return 0; }
void *glLightf(void) { return 0; }
void *glLightfv(void) { return 0; }
void *glLineStipple(void) { return 0; }
void *glLineWidth(void) { return 0; }
void *glListBase(void) { return 0; }
void *glLoadIdentity(void) { return 0; }
void *glLoadMatrixf(void) { return 0; }
void *glLogicOp(void) { return 0; }
void *glMaterialf(void) { return 0; }
void *glMaterialfv(void) { return 0; }
void *glMatrixMode(void) { return 0; }
void *glNewList(void) { return 0; }
void *glNormalPointer(void) { return 0; }
void *glPixelStorei(void) { return 0; }
void *glPixelTransferi(void) { return 0; }
void *glPointSize(void) { return 0; }
void *glPolygonMode(void) { return 0; }
void *glPolygonOffset(void) { return 0; }
void *glPolygonStipple(void) { return 0; }
void *glRasterPos2i(void) { return 0; }
void *glRasterPos3fv(void) { return 0; }
void *glReadBuffer(void) { return 0; }
void *glReadPixels(void) { return 0; }
void *glScissor(void) { return 0; }
void *glShadeModel(void) { return 0; }
void *glStencilFunc(void) { return 0; }
void *glStencilMask(void) { return 0; }
void *glStencilOp(void) { return 0; }
void *glTexCoordPointer(void) { return 0; }
void *glTexEnvi(void) { return 0; }
void *glTexGenfv(void) { return 0; }
void *glTexGeni(void) { return 0; }
void *glTexImage1D(void) { return 0; }
void *glTexImage2D(void) { return 0; }
void *glTexParameterf(void) { return 0; }
void *glTexParameterfv(void) { return 0; }
void *glTexParameteri(void) { return 0; }
void *glTexParameteriv(void) { return 0; }
void *glTexSubImage1D(void) { return 0; }
void *glTexSubImage2D(void) { return 0; }
void *glVertexPointer(void) { return 0; }
void *glViewport(void) { return 0; }
void *glXChooseFBConfig(void) { return 0; }
void *glXChooseVisual(void) { return 0; }
void *glXCreateContext(void) { return 0; }
void *glXCreateNewContext(void) { return 0; }
void *glXCreateWindow(void) { return 0; }
void *glXDestroyContext(void) { return 0; }
void *glXGetClientString(void) { return 0; }
void *glXGetConfig(void) { return 0; }
void *glXGetCurrentContext(void) { return 0; }
void *glXGetCurrentDisplay(void) { return 0; }
void *glXGetCurrentDrawable(void) { return 0; }
void *glXGetProcAddress(void) { return 0; }
void *glXGetProcAddressARB(void) { return 0; }
void *glXGetVisualFromFBConfig(void) { return 0; }
void *glXIsDirect(void) { return 0; }
void *glXMakeContextCurrent(void) { return 0; }
void *glXMakeCurrent(void) { return 0; }
void *glXQueryContext(void) { return 0; }
void *glXQueryExtension(void) { return 0; }
void *glXQueryExtensionsString(void) { return 0; }
void *glXQueryServerString(void) { return 0; }
void *glXQueryVersion(void) { return 0; }
void *glXSwapBuffers(void) { return 0; }
void *glXWaitGL(void) { return 0; }
